# Generated by Django 4.2.3 on 2023-07-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="McBlog!", max_length=255),
        ),
    ]
